bookproject/bookproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    path('books/', include('books.urls', namespace='books')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

bookproject/books/urls.py
from django.urls import include, path, re_path

from . import views

app_name = 'books'

urlpatterns = [
    path('',
        view=views.BookListView.as_view(),
        name='index'),
    path('create/',
        view=views.BookCreateView.as_view(),
        name='create'),
    path('<str:isbn>/',
        view=views.BookDetailView.as_view(),
        name='detail'),
    path('update/<str:isbn>/',
        view=views.BookUpdateView.as_view(),
        name='update'),
    re_path(r'^delete/(?P<isbn>[\d\-]+)/$',
        view=views.BookDeleteView.as_view(),
        name='delete'),
]

bookproject/books/models.py
from django.urls import reverse
from django.db import models

from django.utils.translation import ugettext_lazy as _


class Book(models.Model):
    #  TODO: Do not forget to add a validator for isbn field,
    #  it may only contain digits and hyphens!
    isbn = models.CharField(_('ISBN'), max_length=13, unique=True)
    title = models.CharField(_('Book\'s title'), max_length=128)
    publisher = models.CharField(_('Publisher'), max_length=64)
    author = models.CharField(_('Author'), max_length=64)
    pages = models.IntegerField(_('Pages'), default=0)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = "Books"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:detail', kwargs={'isbn': self.isbn})

bookproject/books/views.py
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView

from .models import Book


class BookListView(ListView):
    """Show all books."""

    model = Book


class BookDetailView(DetailView):
    """Show the requested book."""

    model = Book
    pk_url_kwarg = "isbn"
    template_name = "books/book_detail.html"

    def get_object(self):
        return self.model.objects.get(isbn=self.kwargs['isbn'])


class BookCreateView(CreateView):
    """Create a new book."""

    model = Book
    fields = '__all__'

    # TODO: add a message on the page if form is valid: 'The book created successfully!'
    # TODO: add a message on the page if form is invalid: 'The creation has failed.'


class BookUpdateView(UpdateView):
    """Update the requested book."""

    model = Book
    fields = '__all__'
    pk_url_kwarg = "isbn"
    template_name = "books/book_form.html"

    def get_object(self):
        return self.model.objects.get(isbn=self.kwargs['isbn'])

    # TODO: add a message on the page if form is valid: 'The book updated successfully!'
    # TODO: add a message on the page if form is invalid: 'The update has failed.'


class BookDeleteView(DeleteView):
    """Delete the requested book."""

    model = Book
    pk_url_kwarg = "isbn"
    template_name = "books/book_confirm_delete.html"

    def get_object(self):
        return self.model.objects.get(isbn=self.kwargs['isbn'])

    # TODO: add a message on the page if form is valid: 'The book deleted successfully!'
    # TODO: add a message on the page if form is invalid: 'The deletion has failed.'

bookproject/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% trans 'BooksCRUDApp' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block css %}
      <link href="{% static 'css/style.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block javascript %}
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
        <script src="js/respond.min.js"></script>
        <script src="js/html5shiv.min.js"></script>
      <![endif]-->
    {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/django-logo.png' %}" width="80" alt="Django Framework"/></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
            <li class="active"><a href="{% url 'books:index' %}">{% trans 'Books' %}</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">

      {% if messages %}
        <div class="messages">
          {% for message in messages %}
            <p class="msg msg-{{ message.tags }}">{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}

      {% block content %}{% endblock %}

        <hr>
        <footer>
            <p>&copy; 2005 - {% now 'Y' %} {% blocktrans %}Django Software Foundation and individual contributors. Django is a registered trademark of the Django Software Foundation.{% endblocktrans %}</p>
        </footer>

    </div> <!-- /container -->

    {% block modal %}{% endblock %}

    {% block scripts %}{% endblock %}

  </body>
</html>


{% comment %}
  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">BooksCRUDApp</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'books:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
{% endcomment %}

bookproject/templates/books/book_confirm_delete.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Book' %}: {% trans 'Delete' %}{% endblock %}

{% block content %}

<h1>{{ object.title }}</h1>


<form class="form-horizontal" method="post" action="{% url 'books:delete' object.isbn %}">
  {% csrf_token %}
  {{ form.as_p }}
  <p>{% trans 'Are you sure you want to delete the book?' %}</p>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">{% trans 'Yes, delete' %}</button>
    </div>
  </div>
</form>
{% endblock %}

bookproject/templates/books/book_detail.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Book' %}: {{ object.title }}{% endblock %}

{% block content %}
<h3>{{ object.title }}</h3>
<div class="row">
  <div class="col-sm-12">
    <dl class="dl-horizontal">
      <dt>Title:</dt>
      <dd>{{ object.title }}</dd>
      <dt>ISBN:</dt>
      <dd>{{ object.isbn }}</dd>
      <dt>Publisher:</dt>
      <dd>{{ object.publisher }}</dd>
      <dt>Author:</dt>
      <dd>{{ object.author }}</dd>
      <dt>Total Pages:</dt>
      <dd>{{ object.pages }}</dd>
    </dl>
  </div>
</div>
{% endblock %}

bookproject/templates/books/book_form.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Book' %}{% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>


<form class="form-horizontal" method="post" 
{% if 'create' in request.path %}
  action="{% url 'books:create' %}"
{% else %}
  action="{% url 'books:update' object.isbn %}"
{% endif %}>
  {% csrf_token %}
  {{ form.as_p }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">
        {% if 'create' in request.path %}{% trans 'Create' %}{% else %}{% trans 'Update' %}{% endif %}
      </button>
    </div>
  </div>
</form>
{% endblock %}

bookproject/templates/books/book_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Books' %}{% endblock %}

{% block content %}
<h3>{% trans 'Books' %}</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th><b>ISBN</b></th>
      <th><b>Title</b></th>
      <th><b>Publisher</b></th>
      <th><b>Author</b></th>
      <th colspan=2><b>Action</b></th>
    </tr>
  </thead>
  <tbody>
    {% for book in book_list %}
    <tr>
      <td>
        <a href="{{ book.get_absolute_url }}">{{ book.isbn }}</a>
      </td>
      <td>{{ book.title }}</td>
      <td>{{ book.publisher }}</td>
      <td>{{ book.author }}</td>
      <td><a href="{% url 'books:update' book.isbn %}">Edit</a></td>
      <td><a href="{% url 'books:delete' book.isbn %}">Delete</a></td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan=6><a href="{% url 'books:create' %}">Add new book</a></td>
    </tr>
  </tbody>
</table>
{% endblock content %}

bookproject/templates/pages/home.html
{% extends 'base.html' %}
{% load static i18n %}

<div class="jumbotron">
    <h1>{% blocktrans %}Welcome to Django Framework{% endblocktrans %}</h1>
    <p>{% blocktrans %}Congratulations! You have successfully installed the Books CRUD App. You are currently running Django Framework.{% endblocktrans %}
    <p><a class="btn btn-success btn-lg" href="https://github.com/django/django" target="_blank">{% blocktrans %}Fork Django on GitHub{% endblocktrans %} &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{% blocktrans %}Follow Development{% endblocktrans %}</h3>
            </div>
            <div class="panel-body">
                <p>{% blocktrans %}Django is under active development...{% endblocktrans %}</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{% blocktrans %}Discover Modules{% endblocktrans %}</h3>
            </div>
            <div class="panel-body">
                <p>{% blocktrans %}The community is working on...{% endblocktrans %}</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{% blocktrans %}Help &amp; Support{% endblocktrans %}</h3>
            </div>
            <div class="panel-body">
                <p>{% blocktrans %}If you need any help or support while developing with Django, you may reach us via...{% endblocktrans %}</p>
            </div>
        </div>
    </div>

</div>